import { useState } from 'react';
import { Link } from 'react-router-dom';
import Alert from '../components/Alert.jsx';
import { ticketApi } from '../services/api.js';

const initial = { customer_name: '', customer_email: '', subject: '', description: '' };
export default function CreateTicket() {
  const [form, setForm] = useState(initial); const [errors, setErrors] = useState({}); const [result, setResult] = useState(null); const [serverError, setServerError] = useState(''); const [saving, setSaving] = useState(false);
  const validate = () => { const next = {}; Object.entries(form).forEach(([key, value]) => { if (!value.trim()) next[key] = 'This field is required.'; }); if (form.customer_email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.customer_email)) next.customer_email = 'Enter a valid email address.'; setErrors(next); return !Object.keys(next).length; };
  const submit = async (e) => { e.preventDefault(); setResult(null); setServerError(''); if (!validate()) return; setSaving(true); try { const response = await ticketApi.create(form); setResult(response); setForm(initial); } catch (err) { setServerError(err.message); } finally { setSaving(false); } };
  const field = (key, label, type = 'text') => <label className="label">{label}<input type={type} className={`input ${errors[key] ? 'border-red-400' : ''}`} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} />{errors[key] && <span className="mt-1 block text-xs text-red-600">{errors[key]}</span>}</label>;
  return <section className="mx-auto max-w-3xl"><Link to="/" className="text-sm font-medium text-cyan-800 hover:underline">← Back to tickets</Link><h1 className="mt-4 text-3xl font-bold tracking-tight text-ink">Create support ticket</h1><p className="mt-2 text-slate-600">Record a new customer issue. It will begin with an Open status.</p>{result && <div className="mt-5"><Alert>Ticket <Link className="font-bold underline" to={`/tickets/${result.ticket_id}`}>{result.ticket_id}</Link> was created successfully.</Alert></div>}{serverError && <div className="mt-5"><Alert type="error">{serverError}</Alert></div>}<form onSubmit={submit} noValidate className="card mt-6 space-y-5 p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2">{field('customer_name', 'Customer name')}{field('customer_email', 'Customer email', 'email')}</div>{field('subject', 'Issue title / subject')}<label className="label">Issue description<textarea className={`input min-h-36 resize-y ${errors.description ? 'border-red-400' : ''}`} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} />{errors.description && <span className="mt-1 block text-xs text-red-600">{errors.description}</span>}</label><div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><Link className="button-secondary" to="/">Cancel</Link><button disabled={saving} className="button-primary">{saving ? 'Creating…' : 'Create ticket'}</button></div></form></section>;
}
